sonar.projectKey=Desafio-T-cnico-Full-Stack---Leet
sonar.projectName=Desafio Técnico Full Stack - Leet

sonar.sources=app,resources/js,resources/views,routes
sonar.tests=tests,resources/js/tests

sonar.exclusions=\
resources/js/tests/**,\
vendor/**,\
node_modules/**,\
storage/**,\
bootstrap/cache/**,\
public/build/**

sonar.sourceEncoding=UTF-8